controllers/SiteController.php
<?php
namespace app\controllers;
use app\models\Articles;
use app\models\FeedbackModel;
use app\models\UploadForm;
use yii\db\ActiveRecord;
use yii\filters\AccessControl;
use yii\web\Controller;
use Yii;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{

    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
        ];
    }


    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $this->view->title = 'Misha Hodovanuk';
        return $this->render('index.twig');
    }

    public function actionInfo()
    {
        //FB::send();
        $model = Articles::find()->orderBy(['date' => SORT_DESC])->all();
        $this->view->title = 'Articles';
        return $this->render('info', ['model' => $model]);
    }

    public function actionAbout()
    {
        $this->view->title = 'About';
        return $this->render('about.twig');
    }

    public function actionFeedback()
    {
        $this->view->title = 'Feed back';
        $model = new FeedbackModel();
        if ($model->load(Yii::$app->request->post()) && $model->contact()) {
            Yii::$app->session->setFlash('feedback_success');
            return $this->render('state.twig');
        }
        return $this->render('feedback', ['model' => $model]);
    }



    public function actionArticle($id)
    {
        $model = Articles::findOne($id);
        return $this->render('article.twig', ['model' => $model]);
    }

    public function actionPortfolio()
    {
        $this->view->title = 'Portfolio';
        return $this->render('portfolio.twig');
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionUpdate($id)
    {
        if(Yii::$app->user->isGuest)
        {
            return $this->redirect('login');
        }
        $model=Articles::findOne($id);
        if($model->load(Yii::$app->request->post())&&$model->save())
        {
            Yii::$app->session->setFlash('update_success');
            return $this->render('state.twig');
        }
        return $this->render('update.twig',['model' => $model]);
    }

    public function actionCreateart()
    {
        $this->view->title = 'Create article';
        $model = new Articles();
        if($model->load(Yii::$app->request->post()))
        {
            $model->image=UploadedFile::getInstance($model,'image');
            if($model->validate())
            {
                $model->image->saveAs('uploads/' . $model->image->baseName . '.' . $model->image->extension);
                if($model->save())
                {
                 Yii::$app->session->setFlash('article_created');
                 return $this->render('state.twig');
                }
            }
        }
        return $this->render('create_article.twig', ['model' =>$model]);
    }

    public function actionLogint()
    {
        return $this->render('login.twig');
    }


    public function actionArticles()
    {
        $this->view->title="Articles";
        $model = Articles::find()->orderBy(['date' => SORT_DESC])->all();
        return $this->render('articles.twig',['model' => $model]);
    }

    public function actionDelete($id)
    {
        if(Yii::$app->user->isGuest)
        {
            return $this->redirect('login');
        }
        else {

                $model = Articles::findOne($id);
                $this->view->title = "Delete " . $model->title;
                if ($model->delete()) {
                Yii::$app->session->setFlash('delete');
                return $this->render('state.twig');
                }
            }
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <script src="https://vk.com/js/api/openapi.js?139" type="text/javascript"></script>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
       /* 'brandLabel' =>Html::img('/web/image/life.gif',['class'=>'mainimg']),
        'brandUrl' => Yii::$app->homeUrl,*/
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
   echo Nav::widget([
       'options'=>['class'=>'navbar-nav navbar-left'],
        'items'=>[
                //'label'=>Html::img('/web/image/life.gif',['class'=>'mainimg']),
            Html::a(Html::img('/web/image/life.gif',['class'=>'mainimg']),['/site/index']),
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
                ['label'=>'Articles','url'=>['/site/articles']],
            ['label'=>'Portfolio','url'=>['/site/portfolio']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' =>'Feedback','url'=>['/site/feedback']],
            Yii::$app->user->isGuest ? (
            ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Mikhaylo Hodovanuk <?= date('Y') ?></p>
        <div class="pull-right">
            <img id="steam" src="/web/image/steam.png" class="fedimg" title="My steam account">
            <img id="vkcom" src="/web/image/facebook.png" class="fedimg" title="My VK account">
            <img id="facebook" src="/web/image/vk.png" class="fedimg" title="My facebook account">
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>